2020-06-09 15:45:11,818 | INFO | Запуск программы
2020-06-09 15:45:13,855 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 13, in check_connection
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-09 15:59:19,097 | INFO | Запуск программы
2020-06-09 16:38:51,620 | INFO | Запуск программы
2020-06-09 16:48:29,584 | INFO | Запуск программы
2020-06-09 16:49:11,643 | INFO | Запуск программы
2020-06-09 16:49:40,426 | INFO | Запуск программы
2020-06-09 16:50:11,836 | INFO | Запуск программы
2020-06-09 16:52:16,467 | INFO | Запуск программы
2020-06-09 16:55:02,458 | INFO | Запуск программы
2020-06-09 16:56:17,987 | INFO | Запуск программы
2020-06-09 17:05:19,177 | INFO | Запуск программы
2020-06-09 17:05:22,471 | WARNING | Запрос не отправлен
2020-06-09 17:05:25,712 | WARNING | Запрос не отправлен
2020-06-09 17:05:28,977 | WARNING | Запрос не отправлен
2020-06-09 17:05:32,199 | WARNING | Запрос не отправлен
2020-06-09 17:05:35,426 | WARNING | Запрос не отправлен
2020-06-09 17:05:38,641 | WARNING | Запрос не отправлен
2020-06-09 17:05:41,886 | WARNING | Запрос не отправлен
2020-06-09 17:06:24,523 | INFO | Запуск программы
2020-06-09 17:08:11,284 | INFO | Запуск программы
2020-06-09 17:08:16,468 | WARNING | Запрос не отправлен
2020-06-09 17:08:21,565 | WARNING | Запрос не отправлен
2020-06-09 17:09:37,181 | INFO | Запуск программы
2020-06-09 17:09:42,327 | WARNING | Запрос не отправлен
2020-06-09 17:09:47,380 | WARNING | Запрос не отправлен
2020-06-09 17:09:55,395 | INFO | Запуск программы
2020-06-09 17:10:44,982 | INFO | Запуск программы
2020-06-09 17:10:50,125 | WARNING | Запрос не отправлен
2020-06-09 17:11:59,323 | INFO | Запуск программы
2020-06-09 17:12:38,693 | INFO | Запуск программы
2020-06-09 17:13:17,859 | INFO | Запуск программы
2020-06-09 17:13:57,299 | INFO | Запуск программы
2020-06-09 17:14:26,336 | INFO | Запуск программы
2020-06-09 17:15:07,616 | INFO | Запуск программы
2020-06-09 17:15:23,895 | INFO | Запуск программы
2020-06-09 17:15:29,100 | WARNING | Запрос не отправлен
2020-06-09 17:15:34,236 | WARNING | Запрос не отправлен
2020-06-09 17:15:39,334 | WARNING | Запрос не отправлен
2020-06-09 17:15:58,597 | INFO | Запуск программы
2020-06-09 17:16:25,049 | INFO | Запуск программы
2020-06-09 17:17:33,576 | INFO | Запуск программы
2020-06-09 17:17:38,715 | WARNING | Запрос не отправлен
2020-06-09 17:17:54,695 | INFO | Запуск программы
2020-06-09 17:19:17,594 | INFO | Запуск программы
2020-06-09 17:19:31,778 | INFO | Запуск программы
2020-06-09 17:20:29,733 | WARNING | Не установлено соединение TCP
2020-06-09 17:21:06,698 | INFO | Запуск программы
2020-06-09 17:21:08,719 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 13, in check_connection
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-09 17:21:21,720 | WARNING | Не установлено соединение TCP
2020-06-09 17:21:21,722 | WARNING | Запрос не отправлен
2020-06-09 17:21:23,736 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 13, in check_connection
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-09 17:21:36,728 | WARNING | Не установлено соединение TCP
2020-06-09 17:21:36,729 | WARNING | Запрос не отправлен
2020-06-09 17:21:39,880 | WARNING | Запрос не отправлен
2020-06-09 17:21:42,970 | WARNING | Запрос не отправлен
2020-06-09 17:21:46,015 | WARNING | Запрос не отправлен
2020-06-09 17:21:49,105 | WARNING | Запрос не отправлен
2020-06-10 09:25:52,638 | INFO | Запуск программы
2020-06-10 09:25:55,750 | WARNING | Запрос не отправлен
2020-06-10 09:25:58,771 | WARNING | Запрос не отправлен
2020-06-10 09:28:25,382 | INFO | Запуск программы
2020-06-10 09:29:20,483 | INFO | Запуск программы
2020-06-10 10:05:07,753 | INFO | Запуск программы
2020-06-10 10:20:25,592 | INFO | Запуск программы
2020-06-10 10:20:58,122 | INFO | Запуск программы
2020-06-10 10:21:51,318 | INFO | Запуск программы
2020-06-10 10:23:12,538 | INFO | Запуск программы
2020-06-10 10:27:09,342 | INFO | Запуск программы
2020-06-10 10:27:15,286 | INFO | Запуск программы
2020-06-10 10:27:38,260 | INFO | Запуск программы
2020-06-10 10:28:28,539 | INFO | Запуск программы
2020-06-10 10:28:55,538 | INFO | Запуск программы
2020-06-10 17:14:48,518 | INFO | Запуск программы
2020-06-10 17:14:50,642 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 13, in check_connection
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-10 17:15:03,636 | WARNING | Не установлено соединение TCP
2020-06-10 17:15:03,638 | WARNING | Запрос не отправлен
2020-06-10 17:15:05,649 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 13, in check_connection
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-10 17:15:18,646 | WARNING | Не установлено соединение TCP
2020-06-10 17:15:18,648 | WARNING | Запрос не отправлен
2020-06-10 17:15:20,659 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 13, in check_connection
    s.connect((HOST, PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-10 17:15:33,666 | WARNING | Не установлено соединение TCP
2020-06-10 17:15:33,667 | WARNING | Запрос не отправлен
2020-06-10 17:16:03,601 | INFO | Запуск программы
2020-06-10 17:16:08,762 | WARNING | Запрос не отправлен
2020-06-10 17:16:13,844 | WARNING | Запрос не отправлен
2020-06-10 17:16:18,947 | WARNING | Запрос не отправлен
2020-06-10 17:16:25,972 | WARNING | Запрос не отправлен
2020-06-10 17:16:39,313 | INFO | Запуск программы
2020-06-10 17:17:11,091 | INFO | Запуск программы
2020-06-10 17:17:33,837 | INFO | Запуск программы
2020-06-10 17:18:16,302 | INFO | Запуск программы
2020-06-10 17:18:35,817 | INFO | Запуск программы
2020-06-10 17:19:16,822 | INFO | Запуск программы
2020-06-10 17:19:38,825 | INFO | Запуск программы
2020-06-10 17:22:00,416 | INFO | Запуск программы
2020-06-10 17:23:04,614 | INFO | Запуск программы
2020-06-10 17:23:33,835 | INFO | Запуск программы
2020-06-11 10:02:26,718 | INFO | Запуск программы
2020-06-11 11:33:13,221 | INFO | Запуск программы
2020-06-11 11:48:51,084 | INFO | Запуск программы
2020-06-11 11:50:47,377 | INFO | Запуск программы
2020-06-11 11:53:11,083 | INFO | Запуск программы
2020-06-11 11:55:20,568 | INFO | Запуск программы
2020-06-11 11:55:39,219 | INFO | Запуск программы
2020-06-11 11:55:51,195 | INFO | Запуск программы
2020-06-11 11:56:32,331 | INFO | Запуск программы
2020-06-11 11:58:38,158 | INFO | Запуск программы
2020-06-11 11:59:32,556 | INFO | Запуск программы
2020-06-11 12:00:49,482 | INFO | Запуск программы
2020-06-11 12:01:14,418 | INFO | Запуск программы
2020-06-11 12:01:26,618 | INFO | Запуск программы
2020-06-11 12:01:39,733 | INFO | Запуск программы
2020-06-11 12:03:05,842 | INFO | Запуск программы
2020-06-11 12:03:21,884 | INFO | Запуск программы
2020-06-11 12:04:46,772 | INFO | Запуск программы
2020-06-11 12:04:48,780 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 40, in check_connection
    s.connect((self.HOST, self.PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-11 12:05:01,780 | WARNING | Не установлено соединение TCP
2020-06-11 12:05:01,780 | WARNING | Запрос не отправлен
2020-06-11 12:05:03,783 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Roman\Documents\Работа\replicator_client\web_connector.py", line 40, in check_connection
    s.connect((self.HOST, self.PORT))
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2020-06-11 12:05:16,785 | WARNING | Не установлено соединение TCP
2020-06-11 12:05:16,786 | WARNING | Запрос не отправлен
2020-06-11 12:06:03,658 | INFO | Запуск программы
2020-06-11 12:06:44,739 | INFO | Запуск программы
2020-06-11 12:07:13,257 | INFO | Запуск программы
2020-06-11 12:12:12,618 | INFO | Запуск программы
2020-06-11 12:12:39,406 | INFO | Запуск программы
2020-06-11 12:13:14,259 | INFO | Запуск программы
2020-06-11 12:14:48,901 | INFO | Запуск программы
2020-06-11 12:14:55,989 | INFO | Запуск программы
2020-06-11 12:16:33,709 | INFO | Запуск программы
